modLoader="javafml"

loaderVersion="[36,)"

license="Apache License Version 2.0"

issueTrackerURL="https://discord.com/invite/SVjZbVb4SU"

[[mods]]
itemIcon="pvz:flag"

configBackground="pvz:textures/blocks/Sunflower.png"

modId="pvz"

version="4.0.1"

displayName="Plants Vs Zombies"

displayURL="https://www.curseforge.com/minecraft/mc-mods/plants-vs-zombies-mod-reborn"

logoFile="logo.png"

credits="Thanks for this mod goes to countrygamer for making the og mod"

authors=["RedRoseWarrior1 aka DevMaster1015 for 1.16.5+","countrygamer for all versions below 1.16.5"]

description='''
Brings PVZ to Minecraft
'''

# Base Forge
[[dependencies.pvz]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

# Base Minecraft
[[dependencies.pvz]]
    modId="minecraft"
    mandatory=true
versionRange="[1.16.5,1.17]"
    ordering="NONE"
    side="BOTH"
